name: Ruff Check

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - '**'

jobs:
  ruff:
    runs-on: ubuntu-latest  # Ruff is fast and cross-platform, use Linux to save minutes

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Run ruff check
      - name: Run Ruff linter
        uses: astral-sh/ruff-action@v3
        with:
          args: check --output-format=github
